spring.data.mongodb.uri=mongodb+srv://wtc_user:wtc_password123@challenge-wtc.vwerukw.mongodb.net/challenge_wtc?retryWrites=true&w=majority&appName=Challenge-WTC
spring.application.name=challengebackend
server.port=8080
