# --- CONFIGURAÇÃO MONGODB ---
spring.data.mongodb.uri=mongodb+srv://wtc_user:wtc_password123@challenge-wtc.vwerukw.mongodb.net/challenge_wtc?retryWrites=true&w=majority&appName=Challenge-WTC
# Mantemos desativado por enquanto para permitir que a limpeza manual ocorra sem crashar no boot.
spring.data.mongodb.auto-index-creation=false

spring.application.name=challengebackend
server.port=8080

# --- DEPURAÇÃO PROFISSIONAL (Debug Logs) ---
# Mostra no console do servidor o motivo de cada requisição ser aceita ou negada.
logging.level.org.springframework.security=DEBUG
logging.level.org.springframework.web=DEBUG
